//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSISTANCE
    {
        public decimal ID_ASSISTANCE { get; set; }
        public string ID_EMPLOYEE { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime EXIT_HOUR { get; set; }
        public System.DateTime ENTRY_HOUR { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
