//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BodegaEntities : DbContext
    {
        public BodegaEntities()
            : base("name=BodegaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASSISTANCE> ASSISTANCE { get; set; }
        public virtual DbSet<BRANCH> BRANCH { get; set; }
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<DETAIL> DETAIL { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<EMPLOYEE_BRANCH> EMPLOYEE_BRANCH { get; set; }
        public virtual DbSet<INCLUDE> INCLUDE { get; set; }
        public virtual DbSet<OFFER> OFFER { get; set; }
        public virtual DbSet<PAYMENT_METHOD> PAYMENT_METHOD { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<REQUEST> REQUEST { get; set; }
        public virtual DbSet<SALE> SALE { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIER { get; set; }
        public virtual DbSet<TURN> TURN { get; set; }
    
        public virtual int PRODUCT_MORE_SALES(Nullable<decimal> p_NUMBER)
        {
            var p_NUMBERParameter = p_NUMBER.HasValue ?
                new ObjectParameter("P_NUMBER", p_NUMBER) :
                new ObjectParameter("P_NUMBER", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRODUCT_MORE_SALES", p_NUMBERParameter);
        }
    
        public virtual int SALE_HISTORY_BY_EMPLOYEE(string p_ID_EMPLOYEE, ObjectParameter p_SALE_DATE, ObjectParameter p_PAY_AMOUNT, ObjectParameter p_ID_METHOD)
        {
            var p_ID_EMPLOYEEParameter = p_ID_EMPLOYEE != null ?
                new ObjectParameter("P_ID_EMPLOYEE", p_ID_EMPLOYEE) :
                new ObjectParameter("P_ID_EMPLOYEE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SALE_HISTORY_BY_EMPLOYEE", p_ID_EMPLOYEEParameter, p_SALE_DATE, p_PAY_AMOUNT, p_ID_METHOD);
        }
    }
}
