//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_BRANCH
    {
        public string ID_EMPLOYEE { get; set; }
        public decimal ID_BRANCH { get; set; }
        public decimal ID_EMPLOYEE_BRANCH { get; set; }
        public System.DateTime HIRE_DATE { get; set; }
        public Nullable<System.DateTime> DISMISS_DATE { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
