//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.ASSISTANCE = new HashSet<ASSISTANCE>();
            this.EMPLOYEE_BRANCH = new HashSet<EMPLOYEE_BRANCH>();
            this.REQUEST = new HashSet<REQUEST>();
            this.SALE = new HashSet<SALE>();
        }
    
        public string ID_EMPLOYEE { get; set; }
        public Nullable<decimal> ID_TURN { get; set; }
        public string MOTHER_LASTNAME { get; set; }
        public string FATHER_LASTNAME { get; set; }
        public string UBIGEO { get; set; }
        public string TELEPHONE { get; set; }
        public string TYPE { get; set; }
        public byte[] PHOTO { get; set; }
        public string E_MAIL { get; set; }
        public string PASSWORD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSISTANCE> ASSISTANCE { get; set; }
        public virtual TURN TURN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_BRANCH> EMPLOYEE_BRANCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST> REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALE> SALE { get; set; }
    }
}
