//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFER
    {
        public decimal ID_OFFER { get; set; }
        public string ID_PRODUCT { get; set; }
        public string OFFER1 { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
