//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALE()
        {
            this.DETAIL = new HashSet<DETAIL>();
        }
    
        public string ID_SALE { get; set; }
        public string ID_EMPLOYEE { get; set; }
        public decimal ID_BRANCH { get; set; }
        public decimal ID_PAYMENT_METHOD { get; set; }
        public System.DateTime SALE_DATE { get; set; }
        public decimal GIVEN_AMOUNT { get; set; }
        public decimal CHANGE { get; set; }
        public Nullable<decimal> PAY_AMOUNT { get; set; }
    
        public virtual BRANCH BRANCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL> DETAIL { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PAYMENT_METHOD PAYMENT_METHOD { get; set; }
    }
}
